apiVersion: v1
kind: Secret
metadata:
  name: turbonomic-credentials
  namespace: turbo
type: Opaque
data:
  # username: #####<replace with base64 encoded value>
  # password: #####<replace with base64 encoded value>
  clientid: #####<replace with base64 encoded value>
  clientsecret: #####<replace with base64 encoded value>
